image:
  file: .gitpod.Dockerfile

tasks:
  - init: |
      # Aggiungi Flutter al PATH
      export PATH="$HOME/flutter/bin:$PATH"

      # Mostra Flutter per verifica
      flutter --version

      # Accetta licenze Android
      yes | flutter doctor --android-licenses

      # Verifica tutto
      flutter doctor -v
