# Usa il Dockerfile personalizzato
image:
  file: .gitpod.Dockerfile

tasks:
  - name: Setup Flutter
    init: |
      cd my_library_position
      flutter pub get

vscode:
  extensions:
    - Dart-Code.flutter
    - Dart-Code.dart-code
