
image:
  file: .gitpod.Dockerfile

tasks:
  - name: Setup Flutter
    init: |
      flutter --version
      flutter pub get
    command: |
      echo "Workspace pronto! Per avviare il progetto:"
      echo "flutter run -d chrome"

vscode:
  extensions:
    - Dart-Code.dart-code
    - Dart-Code.flutter
